### PR TITLE
[BUG] : Dimensions getting removed when no timeseries field is present

### LINKED ISSUE #942: [BUG] : Dimensions getting removed when no timeseries field is present
**What is the bug?**
1. Dimensions getting removed when no timeseries field is present
2. When changing the PPL or editing the existing query the page gets blank

**How can one reproduce the bug?**
1. Go to observability->Event analytics -> Explorer
3. put a ppl query as
source=opensearch_dashboards_sample_data_logs | where response='503' or response='404' | stats count() as ip_count, sum(bytes) as sum_bytes by  response
4.  click Refresh
5. select timeseries for the chart
   here Dimensions gets removed from data configuration panel

6. edit the ppl query for any changes to paste a new ppl query, select another chart from the list
 here the page gets blank and we need to go to some other page apart from observability to  make this work again

Issue 1:
image

Issue 2:
image

@abasatwar @spattnaik

### PR DESCRIPTION
**Pull request by ruchika-narang**
### Description
1. Resolved dimension issue for Time Series
2. Resolved issue of data configuration reset after change of PPL query.

### Issues Resolved
#942 

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts [hunk 1]
```diff
@@ -50,6 +65,71 @@ const getDefaultXYAxisLabels = (vizFields: IField[], visName: string) => {
   return { xaxis: mapXaxis(), yaxis: mapYaxis() };
 };
 
+const getUserConfigs = (userSelectedConfigs: any, vizFields: IField[], visName: string) => {
```
Comment (abasatwar) [inline dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts:68]: avoid any

File: dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts [hunk 2]
```diff
@@ -50,6 +65,71 @@ const getDefaultXYAxisLabels = (vizFields: IField[], visName: string) => {
...
+          },
+        };
+        break;
+      case visChartTypes.Histogram:
+        configOfUser = {
+          ...userSelectedConfigs,
+          dataConfig: {
+            ...userSelectedConfigs?.dataConfig,
+            valueOptions: {
+              dimensions: [{ bucketSize: '', bucketOffset: '' }],
```
Comment (abasatwar) [inline dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts:110]: adding empty values will load chart?

**Review by abasatwar — CHANGES_REQUESTED** [review]

File: dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts (hunk 2 above)
Comment (shankha-das) [reply dashboards-observability/public/components/visualizations/charts/helpers/viz_types.ts:110]: Yes, it will load the chart.

**Review by abasatwar — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]

**Review by joshuali925 — APPROVED** [review]
