### PR TITLE
[BUG]: Unable to save Heatmap Visualization and Query

### LINKED ISSUE #1100: [BUG]: Unable to save Heatmap Visualization and Query
**What is the bug?**
Heatmap visualization and query cannot be saved because of a toast that says Invalid Configuration Options found

**How can one reproduce the bug?**
1. Select any visualization or query.
2. If visualization selected, select heatmap from chart dropdown.
3. Render heatmap by selecting dimensions and series.
4. Try to save visualization by clicking on save.
5. Select panel and name for visualization and click on save, you will see error.

**What is the expected behavior?**
Visualization and query should be saved without getting an error if user has added all the correct data.

**Do you have any screenshots?**
heatmap_save

### PR DESCRIPTION
**Pull request by ruchika-narang**
### Description
Fix applied for save of visualizations and query.

### Issues Resolved
#1100 , #1121, #1167

### Check List
- [ ] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: dashboards-observability/public/components/event_analytics/explorer/explorer.tsx [hunk 1]
```diff
@@ -993,8 +1016,8 @@ export const Explorer = ({
       setToast('Name field cannot be empty.', 'danger');
       return;
     }
-    if (!isValidDataConfigOptionSelected) {
-      setToast('Invalid value options configuration selected.', 'danger');
+    if (!Boolean(isValidValueOptionConfigSelected)) {
```
Comment (mengweieric) [inline dashboards-observability/public/components/event_analytics/explorer/explorer.tsx:1019]: do we need to convert to boolean here? any bug this change is trying to address?

Comment (ruchika-narang) [reply dashboards-observability/public/components/event_analytics/explorer/explorer.tsx]: There was no need of Boolean, removed it.

**Review by mengweieric — APPROVED** [review]

File: dashboards-observability/public/components/event_analytics/explorer/explorer.tsx [hunk 2]
```diff
@@ -751,9 +750,34 @@ export const Explorer = ({
       setTriggerAvailability(false);
     }
   };
-
-  const changeIsValidConfigOptionState = (isValidConfig: boolean) =>
-    setIsValidDataConfigOptionSelected(isValidConfig);
+  const isValidValueOptionConfigSelected = useMemo(() => {
+    const { series = [], dimensions = [], span = {} } = visualizations.data.userConfigs?.dataConfig;
+    const { TreeMap, Gauge, HeatMap, Stats } = VIS_CHART_TYPES;
+    const isValidValueOptionsXYAxes =
```
Comment (pjfitzgibbons) [inline dashboards-observability/public/components/event_analytics/explorer/explorer.tsx:756]: I would normally split up this logic for readability/comprehension purposes.

The end-logic I would want to read would be something like : 
```
const isValidValueOptionsYAxes = VIZ_CONTAIN_XY_AXIS.includes(curVisId as VIS_CHART_TYPES) &&
          (chartDataPresent(series, dimensions) || spanIsPresent(span) )
 ```
 Just an example - comprehension for an engineer who is new or has not read the code in several monthts
 is the higher priority

**Review by kavithacm — DISMISSED** [review]

File: dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx [hunk 3]
```diff
@@ -29,6 +29,12 @@ import {
   DataConfigPanelFieldProps,
 } from '../../../../../../../../common/types/explorer';
 
+const HIDE_ADD_BUTTON_VIZ_TYPES = [
```
Comment (pjfitzgibbons) [inline dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx:32]: Would this bee too many lines to be an inclusion filter instead of an elimination filter?

There are only 20 types or so arent there?

Not sure which way carries better comprehension?

File: dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx [hunk 4]
```diff
@@ -40,10 +46,14 @@ export const DataConfigPanelFields = ({
   handleServiceEdit,
 }: DataConfigPanelFieldProps) => {
   const isAggregation = sectionName === AGGREGATIONS;
-  const isHeatMapAddButton = (name: string) => {
-    if (!list || !isArray(list) || visType !== VIS_CHART_TYPES.HeatMap) return false;
-    return name === AGGREGATIONS ? list.length >= 1 : list.length >= 2;
+  const hideAddButton = (name: string) => {
+    if (!isArray(list) || !HIDE_ADD_BUTTON_VIZ_TYPES.includes(visType)) return false;
```
Comment (pjfitzgibbons) [inline dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx:50]: As above.  I would spend over 1/2 hour reading this code and still have the logic description wrong.

**Comment by mengweieric** [comment]
Please address the comments thanks

**Review by anirudha — APPROVED** [review]

**Comment by mengweieric** [comment]
Please answer/resolve comments.

**Comment by ruchika-narang** [comment]
> Please answer/resolve comments.

I am addressing the comments and will give you the PR by your morning!!

File: dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx (hunk 3 above)
Comment (ruchika-narang) [reply dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx:32]: Here, I think the elimination filter that we are using is a better comprehension because we are trying to find if the string is not an element in the array. Please let me know if you have any better thoughts on this.

File: dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx (hunk 4 above)
Comment (ruchika-narang) [reply dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/data_config_panel_fields.tsx:50]: This function would be modified further in the coming weeks with the new implementation of breakdown for line and scatter. For now have mentioned comments to justify the logic.

**Comment by ruchika-narang** [comment]
I have addressed the comments on this one, you can take a look @mengweieric . Thanks!

**Review by joshuali925 — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]
