### PR TITLE
Bug/color-theme-options: Resolved color theme issue

### LINKED ISSUE #959: [BUG]: Field dropdown in Color Theme section only takes numeric fields
**What is the bug?**
Field dropdown in Color Theme section only takes numeric fields.

**How can one reproduce the bug?**
1.Launch OpenSearch Dashboard UI
   Go to Observability->Event Analytics->Explorer
2. Enter PPL Query and select "Year to date" option from calendar
3. Click Refresh
4. Click on Visualizations tab
5. Select the Vertical bar chart option from chart selector dropdown
6. Click on '+ Add color theme' link
7. Select field from the field dropdown

**What is the expected behavior?**
The Field dropdown should have all the other fields along with numeric ones

**Do you have any screenshots?**
image

@anirudha @mengweieric
cc: @abasatwar @spattnaik

### PR DESCRIPTION
**Pull request by shankha-das**
Signed-off-by: Shankha Das <shankha_das@persistent.com>

### Description
Field dropdown in Color Theme section now shows all fields

### Issues Resolved
#959

### CODE REVIEW

File: dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_color_theme.tsx [hunk 1]
```diff
@@ -36,12 +36,10 @@ export const ConfigColorTheme = ({
...
 
-  const options = fields
-    .filter((item) => NUMERICAL_FIELDS.includes(item.type))
-    .map((item) => ({
-      ...item,
-      label: item.name,
-    }));
+  const options = fields.map((item) => ({
+    ...item,
+    label: item.name,
```
Comment (abasatwar) [inline dashboards-observability/public/components/event_analytics/explorer/visualizations/config_panel/config_panes/config_controls/config_color_theme.tsx:41]: We can add this fix for now.But tickets needs to be on hold till two way implementation is done.

**Review by abasatwar — APPROVED** [review]

**Review by mengweieric — APPROVED** [review]

**Review by ps48 — APPROVED** [review]
